"""Add quote_details to project_pipeline

Revision ID: 48965b2b7ce1
Revises: d17438c1d072
Create Date: 2025-05-26 12:37:49.145821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48965b2b7ce1'
down_revision = 'd17438c1d072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_pipeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_details', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_pipeline', schema=None) as batch_op:
        batch_op.drop_column('quote_details')

    # ### end Alembic commands ###
