"""Add demo client and business analysis fields

Revision ID: 50f7b44dbea2
Revises: 
Create Date: 2025-05-26 16:47:34.568554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f7b44dbea2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wants_demo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('company_website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('use_case_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reference_links', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('number_of_verticals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('demo_verticals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('custom_vertical', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('demo_scheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('next_steps', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_suggestions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wants_business_analysis', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('problem_statement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('case_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stakeholders', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visualization_goal', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resources_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_support_team', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('has_complex_math', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('client_type_tag', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_forms', schema=None) as batch_op:
        batch_op.drop_column('client_type_tag')
        batch_op.drop_column('has_complex_math')
        batch_op.drop_column('has_support_team')
        batch_op.drop_column('resources_status')
        batch_op.drop_column('visualization_goal')
        batch_op.drop_column('stakeholders')
        batch_op.drop_column('case_description')
        batch_op.drop_column('problem_statement')
        batch_op.drop_column('wants_business_analysis')
        batch_op.drop_column('client_suggestions')
        batch_op.drop_column('next_steps')
        batch_op.drop_column('meeting_link')
        batch_op.drop_column('timezone')
        batch_op.drop_column('demo_scheduled_at')
        batch_op.drop_column('custom_vertical')
        batch_op.drop_column('demo_verticals')
        batch_op.drop_column('number_of_verticals')
        batch_op.drop_column('reference_links')
        batch_op.drop_column('use_case_description')
        batch_op.drop_column('company_website')
        batch_op.drop_column('wants_demo')

    # ### end Alembic commands ###
