"""Add quote_total and quote_pdf_url columns

Revision ID: d17438c1d072
Revises: 
Create Date: 2025-05-26 10:06:19.468313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17438c1d072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quote_breakdown', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('quote_pdf_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_forms', schema=None) as batch_op:
        batch_op.drop_column('quote_pdf_url')
        batch_op.drop_column('quote_breakdown')
        batch_op.drop_column('quote_total')

    # ### end Alembic commands ###
